# This is a basic workflow to help you get started with Actions

name: Continous integration Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" , "feature/branch"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: running a custom script
        run: |
           ls -al

      - name: log in to Azure Action
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: test
          resource-group: test_group

      # - run: |
      #     kubectl create namespace githubrg

      - run: |
          kubectl apply -f pod.yaml

      - name: run  az command
        run: |
          az account show
          az group list

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: always()
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: check java version
        run: java -version
      - name: gradle build
        run: gradle build
      - name: gradlew build
        run: ./gradlew build
      - name: docker version
        run: |
          docker -v
          docker
          docker images -a
      - name: docker build
        run: |
          docker build . -t xuanan123/demo-kotlin2.0
          docker images -a
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "."
          push: true
          tags: xuanan123/demo-kotlin2.0